name: MDViewer
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.facundo.mdviewer
    PRODUCT_NAME: MDViewer
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: 13.0
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: macos/Info.plist
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: PFK2TQW42Q
    CODE_SIGN_IDENTITY: Apple Development
    CODE_SIGN_ENTITLEMENTS: macos/MDViewer.entitlements
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  MDViewer:
    type: application
    platform: macOS
    sources:
      - path: Sources/MDViewer
      - path: macos/Assets.xcassets
        buildPhase: resources
      - path: macos/MarkdownDocument.icns
        buildPhase: resources
    scheme:
      gatherCoverageData: false
      testTargets: []
